//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man
    {
        public int Id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Дата_рождения { get; set; }
        public string Дата_смерти { get; set; }
        public string Номер_участка { get; set; }
        public string Номер_могилы { get; set; }
        public string Фотография { get; set; }
        public string Описание { get; set; }
        public string Категория { get; set; }
        public string search { get; set; }
    }
}
